spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dalee
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: a1234567890!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: debug